### ISSUE TITLE
Need to read from Notification Collection

### ISSUE THREAD

**Issue by johnthuss** [nofelmahmood/CKSIncrementalStore#10]
When a push notification is received indicating changes have occurred it is necessary to read from the Notification Collection see if any notifications were dropped.  Since push is "best effort" delivery and only the last notification is delivered while offline it is possible for notifications to be missed.  This was covered in one of the videos from WWDC 2014.  I'm not sure what the API call is for doing this.

**Comment by nofelmahmood** [comment]
Nice suggestion. But I don't think that is required because CKSIncrementalStore uses zone subscriptions for notifications. Even if old notifications get dropped because of any new ones, it doesn't matter because at the end of the day all it needs is a notification to trigger sync. It does not require any information from the notification other than just to trigger sync in response to it's delivery.
